#name of the filter
string name

---
# minimum corner point of axis-aligned bounding box in global frame
geometry_msgs/PointStamped min

# maximum corner point of axis-aligned bounding box in global frame
geometry_msgs/PointStamped max

